"""fix f key

Revision ID: 20863e721ce
Revises: 4a275fbfdbe
Create Date: 2016-10-08 22:29:42.818423

"""

# revision identifiers, used by Alembic.
revision = '20863e721ce'
down_revision = '4a275fbfdbe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
