"""v2 version

Revision ID: 4a275fbfdbe
Revises: 42253da3045
Create Date: 2016-10-08 18:48:25.730483

"""

# revision identifiers, used by Alembic.
revision = '4a275fbfdbe'
down_revision = '42253da3045'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('entry', sa.Column('created_timestamp', sa.DateTime(), nullable=True))
    op.add_column('entry', sa.Column('modified_timestamp', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'modified_timestamp')
    op.drop_column('entry', 'created_timestamp')
    op.drop_column('entry', 'author_id')
    ### end Alembic commands ###
